apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: claim-criminal-injuries-compensation-uat

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: claim-criminal-injuries-compensation-uat
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
    resources:
      - "deployments"
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: claim-criminal-injuries-compensation-uat
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: claim-criminal-injuries-compensation-uat
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io