apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-dev
    spec:
      containers:
        - name: webapp
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cica/cica-repo-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: CW_DCS_URL
              value: http://dcs-service-dev
            - name: CW_DCS_JWT
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_dcs_jwt
            - name: CW_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_cookie_secret
            - name: CW_GA_TRACKING_ID
              value: UA-136710388-2
            - name: CW_URL
              value: https://dev.claim-criminal-injuries-compensation.service.justice.gov.uk
            - name: CW_SESSION_DURATION
              value: '900000'
            - name: CW_LIVECHAT_CHAT_ID
              value: 6221d2d5-b8e2-4103-bc7d-c5f66eb2a3dc
            - name: CW_LIVECHAT_ACTIVE_DAYS
              value: 0,1,2,3,4,5,6
            - name: CW_LIVECHAT_START_TIME
              value: '13:30:00.000'
            - name: CW_LIVECHAT_END_TIME
              value: '13:35:00.000'
  selector:
    matchLabels:
      app: webapp-dev
